#!/bin/bash

function centos(){
  sudo yum install -y yum-utils device-mapper-persistent-data lvm2
  sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  yum list docker-ce --showduplicates | sort -r # 查看版本号
  sudo yum install docker-ce # 或者下面方法
  sudo yum install docker-ce-17.12.0.ce
}

function ubuntu(){
	sudo apt-get update
	sudo dpkg --configure -a
	sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	sudo apt-get update
	sudo apt-get install docker-ce
	docker --version
	sudo docker run hello-world
}

$1
