#!/bin/bash

# OS 	Ubuntu 16.04
# Shell Zsh

docker(){ # CE版本
	sudo apt-get update
	sudo dpkg --configure -a
	sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	sudo apt-get update
	sudo apt-get install docker-ce
	docker --version
	sudo docker run hello-world
}

$1
